# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import lib.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190514_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64, verbose_name='目标城市')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最小查找范围')),
                ('max_distance', models.IntegerField(default=50, verbose_name='最大查找范围')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小交友年龄')),
                ('max_dating_age', models.IntegerField(default=50, verbose_name='最大交友年龄')),
                ('dating_sex', models.CharField(choices=[('female', '女'), ('man', '男')], default='female', max_length=20, verbose_name='匹配的性别')),
                ('vibration', models.BooleanField(default=True, verbose_name='开启震动')),
                ('only_matche', models.BooleanField(default=True, verbose_name='不让为匹配的人看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自动播放视频')),
            ],
            bases=(models.Model, lib.mixins.ModelMixin),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.IntegerField(default=1, verbose_name='出生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_month',
            field=models.IntegerField(default=1, verbose_name='出生月'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(default=2000, verbose_name='出生年'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=100, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenum',
            field=models.CharField(max_length=32, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('female', '女'), ('man', '男')], default='female', max_length=20, verbose_name='性别'),
        ),
    ]
