# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190515_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_distance',
            field=models.IntegerField(default=20, verbose_name='最大查找范围'),
        ),
    ]
